project_id = "rdkgewggphezuvpdmtvv"

[functions.analyze-receipt]
verify_jwt = false

[functions.migrate-categories]
verify_jwt = false

[functions.line-webhook]
verify_jwt = false

[functions.move-id-card]
verify_jwt = false

[functions.receipt-file]
verify_jwt = false
